//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvenFacil.DataBaseConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InvenFacilEntities : DbContext
    {
        public InvenFacilEntities()
            : base("name=InvenFacilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblArticulo> TblArticulos { get; set; }
        public virtual DbSet<TblAuditoria> TblAuditorias { get; set; }
        public virtual DbSet<TblMarca> TblMarcas { get; set; }
        public virtual DbSet<TblPerfile> TblPerfiles { get; set; }
        public virtual DbSet<TblTipoArticulo> TblTipoArticuloes { get; set; }
        public virtual DbSet<TblUsuario> TblUsuarios { get; set; }
        public virtual DbSet<TblEstadoUsuario> TblEstadoUsuarios { get; set; }
    }
}
