//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvenFacil.DataBaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblArticulo
    {
        public int IdArticulo { get; set; }
        public string NombreArticulo { get; set; }
        public Nullable<int> IdTipoArticulo { get; set; }
        public Nullable<int> IdMarca { get; set; }
        public string Modelo { get; set; }
        public string Serial { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<int> IdUsuarioUltimaModificación { get; set; }
    
        public virtual TblMarca TblMarca { get; set; }
        public virtual TblTipoArticulo TblTipoArticulo { get; set; }
        public virtual TblUsuario TblUsuario { get; set; }
    }
}
