//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvenFacil.DataBaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAuditoria
    {
        public int IdAuditoria { get; set; }
        public Nullable<int> IdEmpleado { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string AccionRealizada { get; set; }
        public Nullable<int> IdEmpleadoAfectado { get; set; }
    
        public virtual TblUsuario TblUsuario { get; set; }
        public virtual TblUsuario TblUsuario1 { get; set; }
    }
}
