//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvenFacil.DataBaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTipoArticulo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTipoArticulo()
        {
            this.TblArticulos = new HashSet<TblArticulo>();
        }
    
        public int IdTipoArticulo { get; set; }
        public string TipoArticulo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblArticulo> TblArticulos { get; set; }
    }
}
